# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Peg_GuiDPUgUa.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

class Ui_MainWindow(QMainWindow):
    def __init__(self, *args, **kwargs):
        super(Ui_MainWindow, self).__init__(*args, **kwargs)

        def setupUi(self, MainWindow):
            if not MainWindow.objectName():
                MainWindow.setObjectName(u"MainWindow")
            MainWindow.resize(500, 760)
            MainWindow.setMinimumSize(QSize(500, 760))
            MainWindow.setMaximumSize(QSize(500, 760))
            MainWindow.setCursor(QCursor(Qt.ArrowCursor))
            MainWindow.setMouseTracking(True)
            MainWindow.setWindowTitle(u"Peg Solitaire")
            icon = QIcon()
            icon.addFile(u"com.ssaurel.pegsolitaire.jpg", QSize(), QIcon.Normal, QIcon.Off)
            MainWindow.setWindowIcon(icon)
            MainWindow.setWindowOpacity(1.000000000000000)
            MainWindow.setStyleSheet(u"background-color: rgb(115, 124, 148);")
            MainWindow.setIconSize(QSize(50, 50))
            self.centralwidget = QWidget(MainWindow)
            self.centralwidget.setObjectName(u"centralwidget")
            self.btn_1 = QPushButton(self.centralwidget)
            self.btn_1.setObjectName(u"btn_1")
            self.btn_1.setGeometry(QRect(20, 200, 50, 50))
            self.btn_1.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_1.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_2 = QPushButton(self.centralwidget)
            self.btn_2.setObjectName(u"btn_2")
            self.btn_2.setGeometry(QRect(70, 200, 50, 50))
            self.btn_2.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_2.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_3 = QPushButton(self.centralwidget)
            self.btn_3.setObjectName(u"btn_3")
            self.btn_3.setGeometry(QRect(120, 200, 50, 50))
            self.btn_3.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_3.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_4 = QPushButton(self.centralwidget)
            self.btn_4.setObjectName(u"btn_4")
            self.btn_4.setGeometry(QRect(170, 200, 50, 50))
            self.btn_4.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_4.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_5 = QPushButton(self.centralwidget)
            self.btn_5.setObjectName(u"btn_5")
            self.btn_5.setGeometry(QRect(220, 200, 50, 50))
            self.btn_5.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_5.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_6 = QPushButton(self.centralwidget)
            self.btn_6.setObjectName(u"btn_6")
            self.btn_6.setGeometry(QRect(270, 200, 50, 50))
            self.btn_6.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_6.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_7 = QPushButton(self.centralwidget)
            self.btn_7.setObjectName(u"btn_7")
            self.btn_7.setGeometry(QRect(320, 200, 50, 50))
            self.btn_7.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_7.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_8 = QPushButton(self.centralwidget)
            self.btn_8.setObjectName(u"btn_8")
            self.btn_8.setGeometry(QRect(370, 200, 50, 50))
            self.btn_8.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_8.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_9 = QPushButton(self.centralwidget)
            self.btn_9.setObjectName(u"btn_9")
            self.btn_9.setGeometry(QRect(420, 200, 50, 50))
            self.btn_9.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_9.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_10 = QPushButton(self.centralwidget)
            self.btn_10.setObjectName(u"btn_10")
            self.btn_10.setGeometry(QRect(170, 250, 50, 50))
            self.btn_10.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_10.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_11 = QPushButton(self.centralwidget)
            self.btn_11.setObjectName(u"btn_11")
            self.btn_11.setGeometry(QRect(220, 250, 50, 50))
            self.btn_11.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_11.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_12 = QPushButton(self.centralwidget)
            self.btn_12.setObjectName(u"btn_12")
            self.btn_12.setGeometry(QRect(20, 250, 50, 50))
            self.btn_12.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_12.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_13 = QPushButton(self.centralwidget)
            self.btn_13.setObjectName(u"btn_13")
            self.btn_13.setGeometry(QRect(270, 250, 50, 50))
            self.btn_13.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_13.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_14 = QPushButton(self.centralwidget)
            self.btn_14.setObjectName(u"btn_14")
            self.btn_14.setGeometry(QRect(370, 250, 50, 50))
            self.btn_14.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_14.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_15 = QPushButton(self.centralwidget)
            self.btn_15.setObjectName(u"btn_15")
            self.btn_15.setGeometry(QRect(320, 250, 50, 50))
            self.btn_15.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_15.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_16 = QPushButton(self.centralwidget)
            self.btn_16.setObjectName(u"btn_16")
            self.btn_16.setGeometry(QRect(70, 250, 50, 50))
            self.btn_16.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_16.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_17 = QPushButton(self.centralwidget)
            self.btn_17.setObjectName(u"btn_17")
            self.btn_17.setGeometry(QRect(120, 250, 50, 50))
            self.btn_17.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_17.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_18 = QPushButton(self.centralwidget)
            self.btn_18.setObjectName(u"btn_18")
            self.btn_18.setGeometry(QRect(420, 250, 50, 50))
            self.btn_18.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_18.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_19 = QPushButton(self.centralwidget)
            self.btn_19.setObjectName(u"btn_19")
            self.btn_19.setGeometry(QRect(170, 300, 50, 50))
            self.btn_19.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_19.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_20 = QPushButton(self.centralwidget)
            self.btn_20.setObjectName(u"btn_20")
            self.btn_20.setGeometry(QRect(220, 300, 50, 50))
            self.btn_20.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_20.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_21 = QPushButton(self.centralwidget)
            self.btn_21.setObjectName(u"btn_21")
            self.btn_21.setGeometry(QRect(20, 300, 50, 50))
            self.btn_21.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_21.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_22 = QPushButton(self.centralwidget)
            self.btn_22.setObjectName(u"btn_22")
            self.btn_22.setGeometry(QRect(270, 300, 50, 50))
            self.btn_22.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_22.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_23 = QPushButton(self.centralwidget)
            self.btn_23.setObjectName(u"btn_23")
            self.btn_23.setGeometry(QRect(370, 300, 50, 50))
            self.btn_23.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_23.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_24 = QPushButton(self.centralwidget)
            self.btn_24.setObjectName(u"btn_24")
            self.btn_24.setGeometry(QRect(320, 300, 50, 50))
            self.btn_24.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_24.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_25 = QPushButton(self.centralwidget)
            self.btn_25.setObjectName(u"btn_25")
            self.btn_25.setGeometry(QRect(70, 300, 50, 50))
            self.btn_25.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_25.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_26 = QPushButton(self.centralwidget)
            self.btn_26.setObjectName(u"btn_26")
            self.btn_26.setGeometry(QRect(120, 300, 50, 50))
            self.btn_26.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_26.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_27 = QPushButton(self.centralwidget)
            self.btn_27.setObjectName(u"btn_27")
            self.btn_27.setGeometry(QRect(420, 300, 50, 50))
            self.btn_27.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_27.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_28 = QPushButton(self.centralwidget)
            self.btn_28.setObjectName(u"btn_28")
            self.btn_28.setGeometry(QRect(170, 350, 50, 50))
            self.btn_28.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_28.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_29 = QPushButton(self.centralwidget)
            self.btn_29.setObjectName(u"btn_29")
            self.btn_29.setGeometry(QRect(220, 350, 50, 50))
            self.btn_29.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_29.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_30 = QPushButton(self.centralwidget)
            self.btn_30.setObjectName(u"btn_30")
            self.btn_30.setGeometry(QRect(20, 350, 50, 50))
            self.btn_30.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_30.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_31 = QPushButton(self.centralwidget)
            self.btn_31.setObjectName(u"btn_31")
            self.btn_31.setGeometry(QRect(270, 350, 50, 50))
            self.btn_31.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_31.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_32 = QPushButton(self.centralwidget)
            self.btn_32.setObjectName(u"btn_32")
            self.btn_32.setGeometry(QRect(370, 350, 50, 50))
            self.btn_32.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_32.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_33 = QPushButton(self.centralwidget)
            self.btn_33.setObjectName(u"btn_33")
            self.btn_33.setGeometry(QRect(320, 350, 50, 50))
            self.btn_33.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_33.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_34 = QPushButton(self.centralwidget)
            self.btn_34.setObjectName(u"btn_34")
            self.btn_34.setGeometry(QRect(70, 350, 50, 50))
            self.btn_34.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_34.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_35 = QPushButton(self.centralwidget)
            self.btn_35.setObjectName(u"btn_35")
            self.btn_35.setGeometry(QRect(120, 350, 50, 50))
            self.btn_35.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_35.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_36 = QPushButton(self.centralwidget)
            self.btn_36.setObjectName(u"btn_36")
            self.btn_36.setGeometry(QRect(420, 350, 50, 50))
            self.btn_36.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_36.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_37 = QPushButton(self.centralwidget)
            self.btn_37.setObjectName(u"btn_37")
            self.btn_37.setGeometry(QRect(170, 400, 50, 50))
            self.btn_37.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_37.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_38 = QPushButton(self.centralwidget)
            self.btn_38.setObjectName(u"btn_38")
            self.btn_38.setGeometry(QRect(220, 400, 50, 50))
            self.btn_38.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_38.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_39 = QPushButton(self.centralwidget)
            self.btn_39.setObjectName(u"btn_39")
            self.btn_39.setGeometry(QRect(20, 400, 50, 50))
            self.btn_39.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_39.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_40 = QPushButton(self.centralwidget)
            self.btn_40.setObjectName(u"btn_40")
            self.btn_40.setGeometry(QRect(270, 400, 50, 50))
            self.btn_40.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_40.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_41 = QPushButton(self.centralwidget)
            self.btn_41.setObjectName(u"btn_41")
            self.btn_41.setGeometry(QRect(370, 400, 50, 50))
            self.btn_41.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_41.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_42 = QPushButton(self.centralwidget)
            self.btn_42.setObjectName(u"btn_42")
            self.btn_42.setGeometry(QRect(320, 400, 50, 50))
            self.btn_42.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_42.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_43 = QPushButton(self.centralwidget)
            self.btn_43.setObjectName(u"btn_43")
            self.btn_43.setGeometry(QRect(70, 400, 50, 50))
            self.btn_43.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_43.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_44 = QPushButton(self.centralwidget)
            self.btn_44.setObjectName(u"btn_44")
            self.btn_44.setGeometry(QRect(120, 400, 50, 50))
            self.btn_44.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_44.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_45 = QPushButton(self.centralwidget)
            self.btn_45.setObjectName(u"btn_45")
            self.btn_45.setGeometry(QRect(420, 400, 50, 50))
            self.btn_45.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_45.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_46 = QPushButton(self.centralwidget)
            self.btn_46.setObjectName(u"btn_46")
            self.btn_46.setGeometry(QRect(170, 450, 50, 50))
            self.btn_46.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_46.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_47 = QPushButton(self.centralwidget)
            self.btn_47.setObjectName(u"btn_47")
            self.btn_47.setGeometry(QRect(220, 450, 50, 50))
            self.btn_47.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_47.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_48 = QPushButton(self.centralwidget)
            self.btn_48.setObjectName(u"btn_48")
            self.btn_48.setGeometry(QRect(20, 450, 50, 50))
            self.btn_48.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_48.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_49 = QPushButton(self.centralwidget)
            self.btn_49.setObjectName(u"btn_49")
            self.btn_49.setGeometry(QRect(270, 450, 50, 50))
            self.btn_49.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_49.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_50 = QPushButton(self.centralwidget)
            self.btn_50.setObjectName(u"btn_50")
            self.btn_50.setGeometry(QRect(370, 450, 50, 50))
            self.btn_50.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_50.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_51 = QPushButton(self.centralwidget)
            self.btn_51.setObjectName(u"btn_51")
            self.btn_51.setGeometry(QRect(320, 450, 50, 50))
            self.btn_51.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_51.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_52 = QPushButton(self.centralwidget)
            self.btn_52.setObjectName(u"btn_52")
            self.btn_52.setGeometry(QRect(70, 450, 50, 50))
            self.btn_52.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_52.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_53 = QPushButton(self.centralwidget)
            self.btn_53.setObjectName(u"btn_53")
            self.btn_53.setGeometry(QRect(120, 450, 50, 50))
            self.btn_53.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_53.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_54 = QPushButton(self.centralwidget)
            self.btn_54.setObjectName(u"btn_54")
            self.btn_54.setGeometry(QRect(420, 450, 50, 50))
            self.btn_54.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_54.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_55 = QPushButton(self.centralwidget)
            self.btn_55.setObjectName(u"btn_55")
            self.btn_55.setGeometry(QRect(170, 500, 50, 50))
            self.btn_55.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_55.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_56 = QPushButton(self.centralwidget)
            self.btn_56.setObjectName(u"btn_56")
            self.btn_56.setGeometry(QRect(220, 500, 50, 50))
            self.btn_56.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_56.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_57 = QPushButton(self.centralwidget)
            self.btn_57.setObjectName(u"btn_57")
            self.btn_57.setGeometry(QRect(20, 500, 50, 50))
            self.btn_57.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_57.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_58 = QPushButton(self.centralwidget)
            self.btn_58.setObjectName(u"btn_58")
            self.btn_58.setGeometry(QRect(270, 500, 50, 50))
            self.btn_58.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_58.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_59 = QPushButton(self.centralwidget)
            self.btn_59.setObjectName(u"btn_59")
            self.btn_59.setGeometry(QRect(370, 500, 50, 50))
            self.btn_59.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_59.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_60 = QPushButton(self.centralwidget)
            self.btn_60.setObjectName(u"btn_60")
            self.btn_60.setGeometry(QRect(320, 500, 50, 50))
            self.btn_60.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_60.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_61 = QPushButton(self.centralwidget)
            self.btn_61.setObjectName(u"btn_61")
            self.btn_61.setGeometry(QRect(70, 500, 50, 50))
            self.btn_61.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_61.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_62 = QPushButton(self.centralwidget)
            self.btn_62.setObjectName(u"btn_62")
            self.btn_62.setGeometry(QRect(120, 500, 50, 50))
            self.btn_62.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_62.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_63 = QPushButton(self.centralwidget)
            self.btn_63.setObjectName(u"btn_63")
            self.btn_63.setGeometry(QRect(420, 500, 50, 50))
            self.btn_63.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_63.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_64 = QPushButton(self.centralwidget)
            self.btn_64.setObjectName(u"btn_64")
            self.btn_64.setGeometry(QRect(170, 550, 50, 50))
            self.btn_64.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_64.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_65 = QPushButton(self.centralwidget)
            self.btn_65.setObjectName(u"btn_65")
            self.btn_65.setGeometry(QRect(220, 550, 50, 50))
            self.btn_65.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_65.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_66 = QPushButton(self.centralwidget)
            self.btn_66.setObjectName(u"btn_66")
            self.btn_66.setGeometry(QRect(20, 550, 50, 50))
            self.btn_66.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_66.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_67 = QPushButton(self.centralwidget)
            self.btn_67.setObjectName(u"btn_67")
            self.btn_67.setGeometry(QRect(270, 550, 50, 50))
            self.btn_67.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_67.setStyleSheet(u"background-color: rgb(223, 223, 0);")
            self.btn_68 = QPushButton(self.centralwidget)
            self.btn_68.setObjectName(u"btn_68")
            self.btn_68.setGeometry(QRect(370, 550, 50, 50))
            self.btn_68.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_68.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_69 = QPushButton(self.centralwidget)
            self.btn_69.setObjectName(u"btn_69")
            self.btn_69.setGeometry(QRect(320, 550, 50, 50))
            self.btn_69.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_69.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_70 = QPushButton(self.centralwidget)
            self.btn_70.setObjectName(u"btn_70")
            self.btn_70.setGeometry(QRect(70, 550, 50, 50))
            self.btn_70.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_70.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_71 = QPushButton(self.centralwidget)
            self.btn_71.setObjectName(u"btn_71")
            self.btn_71.setGeometry(QRect(120, 550, 50, 50))
            self.btn_71.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_71.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_72 = QPushButton(self.centralwidget)
            self.btn_72.setObjectName(u"btn_72")
            self.btn_72.setGeometry(QRect(420, 550, 50, 50))
            self.btn_72.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_72.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_73 = QPushButton(self.centralwidget)
            self.btn_73.setObjectName(u"btn_73")
            self.btn_73.setGeometry(QRect(170, 600, 50, 50))
            self.btn_73.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_73.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_74 = QPushButton(self.centralwidget)
            self.btn_74.setObjectName(u"btn_74")
            self.btn_74.setGeometry(QRect(220, 600, 50, 50))
            self.btn_74.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_74.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_75 = QPushButton(self.centralwidget)
            self.btn_75.setObjectName(u"btn_75")
            self.btn_75.setGeometry(QRect(20, 600, 50, 50))
            self.btn_75.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_75.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_76 = QPushButton(self.centralwidget)
            self.btn_76.setObjectName(u"btn_76")
            self.btn_76.setGeometry(QRect(270, 600, 50, 50))
            self.btn_76.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_76.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_77 = QPushButton(self.centralwidget)
            self.btn_77.setObjectName(u"btn_77")
            self.btn_77.setGeometry(QRect(370, 600, 50, 50))
            self.btn_77.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_77.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_78 = QPushButton(self.centralwidget)
            self.btn_78.setObjectName(u"btn_78")
            self.btn_78.setGeometry(QRect(320, 600, 50, 50))
            self.btn_78.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_78.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_79 = QPushButton(self.centralwidget)
            self.btn_79.setObjectName(u"btn_79")
            self.btn_79.setGeometry(QRect(70, 600, 50, 50))
            self.btn_79.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_79.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_80 = QPushButton(self.centralwidget)
            self.btn_80.setObjectName(u"btn_80")
            self.btn_80.setGeometry(QRect(120, 600, 50, 50))
            self.btn_80.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_80.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_81 = QPushButton(self.centralwidget)
            self.btn_81.setObjectName(u"btn_81")
            self.btn_81.setGeometry(QRect(420, 600, 50, 50))
            self.btn_81.setCursor(QCursor(Qt.SizeAllCursor))
            self.btn_81.setStyleSheet(u"background-color: rgb(76, 82, 98);")
            self.btn_restart = QPushButton(self.centralwidget)
            self.btn_restart.setObjectName(u"btn_restart")
            self.btn_restart.setGeometry(QRect(320, 0, 90, 80))
            self.btn_restart.setStyleSheet(u"background-color: rgb(109, 118, 141);")
            icon1 = QIcon()
            icon1.addFile(u"14787197661582004498-128.png", QSize(), QIcon.Normal, QIcon.Off)
            self.btn_restart.setIcon(icon1)
            self.btn_restart.setIconSize(QSize(70, 70))
            self.btn_menu = QPushButton(self.centralwidget)
            self.btn_menu.setObjectName(u"btn_menu")
            self.btn_menu.setGeometry(QRect(410, 0, 90, 80))
            self.btn_menu.setStyleSheet(u"background-color: rgb(109, 118, 141);")
            icon2 = QIcon()
            icon2.addFile(u"2252295991582004497-128.png", QSize(), QIcon.Normal, QIcon.Off)
            self.btn_menu.setIcon(icon2)
            self.btn_menu.setIconSize(QSize(70, 70))
            self.btn_back = QPushButton(self.centralwidget)
            self.btn_back.setObjectName(u"btn_back")
            self.btn_back.setGeometry(QRect(230, 0, 90, 80))
            self.btn_back.setStyleSheet(u"background-color: rgb(109, 118, 141);")
            icon3 = QIcon()
            icon3.addFile(u"1959125971582004485-128.png", QSize(), QIcon.Normal, QIcon.Off)
            self.btn_back.setIcon(icon3)
            self.btn_back.setIconSize(QSize(70, 70))
            self.cmbBox_type = QComboBox(self.centralwidget)
            icon4 = QIcon()
            icon4.addFile(u"photo_2021-01-11_19-53-08.jpg", QSize(), QIcon.Normal, QIcon.Off)
            self.cmbBox_type.addItem(icon4, "")
            icon5 = QIcon()
            icon5.addFile(u"photo_2021-01-11_19-53-00.jpg", QSize(), QIcon.Normal, QIcon.Off)
            self.cmbBox_type.addItem(icon5, "")
            icon6 = QIcon()
            icon6.addFile(u"photo_2021-01-11_19-52-50.jpg", QSize(), QIcon.Normal, QIcon.Off)
            self.cmbBox_type.addItem(icon6, "")
            icon7 = QIcon()
            icon7.addFile(u"photo_2021-01-11_19-52-43.jpg", QSize(), QIcon.Normal, QIcon.Off)
            self.cmbBox_type.addItem(icon7, "")
            icon8 = QIcon()
            icon8.addFile(u"photo_2021-01-11_19-52-30.jpg", QSize(), QIcon.Normal, QIcon.Off)
            self.cmbBox_type.addItem(icon8, "")
            icon9 = QIcon()
            icon9.addFile(u"photo_2021-01-11_19-51-57.jpg", QSize(), QIcon.Normal, QIcon.Off)
            self.cmbBox_type.addItem(icon9, "")
            self.cmbBox_type.setObjectName(u"cmbBox_type")
            self.cmbBox_type.setGeometry(QRect(0, 0, 231, 80))
            self.cmbBox_type.setStyleSheet(u"background-color: rgb(109, 118, 141);")
            self.cmbBox_type.setIconSize(QSize(70, 70))
            MainWindow.setCentralWidget(self.centralwidget)

            self.retranslateUi(MainWindow)

            QMetaObject.connectSlotsByName(MainWindow)
        # setupUi

        def retranslateUi(self, MainWindow):
            self.btn_1.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_3.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_6.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_7.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_8.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_9.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_10.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_11.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_12.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_13.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_14.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_15.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_16.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_17.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_18.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_19.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_20.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_21.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_22.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_23.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_24.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_25.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_26.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_27.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_28.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_29.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_30.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_31.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_32.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_33.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_34.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_35.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_36.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_37.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_38.setText(QCoreApplication.translate("MainWindow", u"69", None))
            self.btn_39.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_40.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_41.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_42.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_43.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_44.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_45.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_46.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_47.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_48.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_49.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_50.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_51.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_52.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_53.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_54.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_55.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_56.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_57.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_58.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_59.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_60.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_61.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_62.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_63.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_64.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_65.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_66.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_67.setText(QCoreApplication.translate("MainWindow", u"1", None))
            self.btn_68.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_69.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_70.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_71.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_72.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_73.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_74.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_75.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_76.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_77.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_78.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_79.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_80.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_81.setText(QCoreApplication.translate("MainWindow", u"0", None))
            self.btn_restart.setText("")
            self.btn_menu.setText("")
            self.btn_back.setText("")
            self.cmbBox_type.setItemText(0, QCoreApplication.translate("MainWindow", u"Classic", None))
            self.cmbBox_type.setItemText(1, QCoreApplication.translate("MainWindow", u"European", None))
            self.cmbBox_type.setItemText(2, QCoreApplication.translate("MainWindow", u"German", None))
            self.cmbBox_type.setItemText(3, QCoreApplication.translate("MainWindow", u"Asymmetrical", None))
            self.cmbBox_type.setItemText(4, QCoreApplication.translate("MainWindow", u"Diamond", None))
            self.cmbBox_type.setItemText(5, QCoreApplication.translate("MainWindow", u"Sguare", None))
            
            pass
        # retranslateUi
    




    